# Generated by Django 4.2.19 on 2025-02-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0002_remove_employee_assigned_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_projects',
            field=models.ManyToManyField(through='graphql_app.EmployeeProjectAssignment', to='graphql_app.project'),
        ),
    ]
