# Generated by Django 4.2.19 on 2025-02-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0003_employee_assigned_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.FloatField(max_length=10),
        ),
    ]
